### ISSUE TITLE
Error after starting a game [LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32)]

### ISSUE THREAD

**Issue by Ebanatnii** [anticitizn/creamlinux#18]
I seem to have done everything correctly, but when I start Stellaris a crash window pops up. Logs below
P.s. I'm not very smart in using Linux systems.
Logs
![изображение](https://github.com/anticitizn/creamlinux/assets/156610304/5234cbbe-4424-40af-aee3-34c92a637e63)

**Comment by filip264CZ9** [comment]
i have this same exact issue and i wanted to ask if u somehow got it working?

**Comment by filip264CZ9** [comment]
@Ebanatnii i have this same exact issue and i wanted to ask if u somehow got it working?

**Comment by anticitizn** [comment]
Hello, I haven't updated Stellaris in some time, will update these days to try this out. We had an issue some versions ago where having outdated DLC files with creamlinux would make Stellaris crash for some reason - are yours up to date? Those errors are normal and completely harmless.

**Comment by anticitizn** [comment]
Hello again, sorry for the late response. I also experienced this with the latest Stellaris version and DLCs - it turned out that some of my files were corrupted even though the Steam file integrity check was passing. I fixed it by completely uninstalling Stellaris, deleting all files, then reinstalling and re-applying creamlinux. The game launched and DLCs worked correctly as usual.
